name: "Close stale issues and PRs"
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "이 이슈는 최근 활동이 없어 stale로 표시됩니다."
          close-issue-message: "이 이슈는 활동이 없어 자동으로 닫힙니다."
          days-before-stale: 0
          days-before-close: 0
          exempt-issue-labels: "bug, enhancement, do-not-stale"
          exempt-pr-labels: "bug, enhancement, do-not-stale"
          exempt-pr-assignees: "sohyun-ku"