name: "Close stale issues and PRs"
on:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been marked with the stale label due to a lack of recent activity.If no further updates are made within 7 days, it will be automatically closed."
          stale-pr-message: "This PR has been marked with the stale label due to a lack of recent activity.If no further updates are made within 7 days, it will be automatically closed."
          days-before-stale: 60
          days-before-close: 7
          stale-issue-labels: "stale"
          stale-pr-labels: "stale"
          exempt-issue-labels: "bug,enhancement,do-not-stale"
          exempt-pr-labels: "bug,enhancement,do-not-stale"
          exempt-pr-assignees: "sohyun-ku"